---
  sudo: required

  language: minimal

  notifications:
    email: false

  branches:
    only:
    - master
    - ci

  before_install:
    ./setup.sh > setup.log 2> /dev/null

  script:
    - ./build.sh > build.log 2> /dev/null